# Generated by Django 5.1.4 on 2024-12-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unis', '0002_uni_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uni',
            name='source',
        ),
    ]
