# Generated by Django 5.1.4 on 2024-12-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unis', '0005_uni_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uni',
            old_name='data',
            new_name='date',
        ),
    ]
