# Generated by Django 5.1.4 on 2024-12-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unis', '0007_uni_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uni',
            name='img',
            field=models.ImageField(blank=True, default='empty.png', upload_to=''),
        ),
    ]
