# Generated by Django 5.1.4 on 2024-12-27 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unis', '0008_alter_uni_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni',
            name='score',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
