# Generated by Django 5.1.4 on 2024-12-27 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unis', '0009_uni_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uni',
            name='score',
        ),
        migrations.AddField(
            model_name='uni',
            name='scoreBudget',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='uni',
            name='scorePaid',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
