# Generated by Django 5.1.4 on 2024-12-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unis', '0010_remove_uni_score_uni_scorebudget_uni_scorepaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
