# Generated by Django 5.1.4 on 2024-12-27 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='scoreBudget',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='scorePaid',
        ),
        migrations.AddField(
            model_name='profile',
            name='userScoreBudget',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='userScorePaid',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
